// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/indiealistic/bethacon/proto/bethacon/bethacon.proto

package bethaconproto

import (
	fmt "fmt"
	health "github.com/indiealistic/bethacon/proto/health"
	_ "github.com/indiealistic/bethacon/proto/status"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/prysmaticlabs/ethereumapis/eth/v1alpha1"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for BethaConService service

func NewBethaConServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for BethaConService service

type BethaConService interface {
	Health(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*health.HealthResponse, error)
	Ping(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*empty.Empty, error)
	// Attester
	GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...client.CallOption) (*GetAttestationResponse, error)
	ProposeAttestation(ctx context.Context, in *ProposeAttestationRequest, opts ...client.CallOption) (*ProposeAttestationResponse, error)
}

type bethaConService struct {
	c    client.Client
	name string
}

func NewBethaConService(name string, c client.Client) BethaConService {
	return &bethaConService{
		c:    c,
		name: name,
	}
}

func (c *bethaConService) Health(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*health.HealthResponse, error) {
	req := c.c.NewRequest(c.name, "BethaConService.Health", in)
	out := new(health.HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bethaConService) Ping(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "BethaConService.Ping", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bethaConService) GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...client.CallOption) (*GetAttestationResponse, error) {
	req := c.c.NewRequest(c.name, "BethaConService.GetAttestation", in)
	out := new(GetAttestationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bethaConService) ProposeAttestation(ctx context.Context, in *ProposeAttestationRequest, opts ...client.CallOption) (*ProposeAttestationResponse, error) {
	req := c.c.NewRequest(c.name, "BethaConService.ProposeAttestation", in)
	out := new(ProposeAttestationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BethaConService service

type BethaConServiceHandler interface {
	Health(context.Context, *empty.Empty, *health.HealthResponse) error
	Ping(context.Context, *empty.Empty, *empty.Empty) error
	// Attester
	GetAttestation(context.Context, *GetAttestationRequest, *GetAttestationResponse) error
	ProposeAttestation(context.Context, *ProposeAttestationRequest, *ProposeAttestationResponse) error
}

func RegisterBethaConServiceHandler(s server.Server, hdlr BethaConServiceHandler, opts ...server.HandlerOption) error {
	type bethaConService interface {
		Health(ctx context.Context, in *empty.Empty, out *health.HealthResponse) error
		Ping(ctx context.Context, in *empty.Empty, out *empty.Empty) error
		GetAttestation(ctx context.Context, in *GetAttestationRequest, out *GetAttestationResponse) error
		ProposeAttestation(ctx context.Context, in *ProposeAttestationRequest, out *ProposeAttestationResponse) error
	}
	type BethaConService struct {
		bethaConService
	}
	h := &bethaConServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&BethaConService{h}, opts...))
}

type bethaConServiceHandler struct {
	BethaConServiceHandler
}

func (h *bethaConServiceHandler) Health(ctx context.Context, in *empty.Empty, out *health.HealthResponse) error {
	return h.BethaConServiceHandler.Health(ctx, in, out)
}

func (h *bethaConServiceHandler) Ping(ctx context.Context, in *empty.Empty, out *empty.Empty) error {
	return h.BethaConServiceHandler.Ping(ctx, in, out)
}

func (h *bethaConServiceHandler) GetAttestation(ctx context.Context, in *GetAttestationRequest, out *GetAttestationResponse) error {
	return h.BethaConServiceHandler.GetAttestation(ctx, in, out)
}

func (h *bethaConServiceHandler) ProposeAttestation(ctx context.Context, in *ProposeAttestationRequest, out *ProposeAttestationResponse) error {
	return h.BethaConServiceHandler.ProposeAttestation(ctx, in, out)
}
